### ISSUE TITLE
How do I use this as a gem dependency?

### ISSUE THREAD

**Issue by rkh** [krypt/krypt#20]
So that it will work on all platforms.

**Comment by emboss** [comment]
Working on that at the very moment. The intention is to use the gemspec platform attribute so that a 'gem install krypt' would pull in the correct dependencies w.r.t whether you're on JRuby or not, and later also probably the OS you're on.

**Comment by rkh** [comment]
Sweet!

**Comment by emboss** [comment]
@rkh Done. `gem install krypt` and `require 'krypt'` should do it now. It should also automatically detect whether it's running on JRuby and choose the correct dependencies automatically.

**Comment by rkh** [comment]
\o/
