### ISSUE TITLE
Issues with krypt when running a rails application on a java application server

### ISSUE THREAD

**Issue by djannot** [krypt/krypt#38]
I have a lot of issues like below when I run the application:

[#|2013-09-03T19:42:30.128+0200|INFO|glassfish3.1.2|javax.enterprise.system.container.web.com.sun.enterprise.web|_ThreadID=19;_ThreadName=Thread-3;|PWC1412: WebModule[null] ServletContext.log():
Krypt::Provider::ServiceNotAvailableError (The requested service is not available):
  gems/gems/krypt-0.0.1/lib/krypt/provider.rb:32:in `new_service'
  gems/gems/krypt-0.0.1/lib/krypt/digest.rb:100:in`new'
  org/jruby/RubyBasicObject.java:1735:in `instance_eval'
  gems/gems/krypt-0.0.1/lib/krypt/digest.rb:101:in`new'
  gems/gems/krypt-0.0.1/lib/krypt/digest.rb:106:in `new'
  gems/gems/krypt-ossl-0.1.0/lib/krypt/ossl/pkcs5.rb:10:in`pbkdf2_hmac_sha1'
  gems/gems/activesupport-4.0.0.rc1/lib/active_support/key_generator.rb:21:in `generate_key'
  gems/gems/activesupport-4.0.0.rc1/lib/active_support/key_generator.rb:38:in`generate_key'
  gems/gems/actionpack-4.0.0.rc1/lib/action_dispatch/middleware/cookies.rb:436:in `initialize'
  gems/gems/actionpack-4.0.0.rc1/lib/action_dispatch/middleware/cookies.rb:159:in`encrypted'
  gems/gems/actionpack-4.0.0.rc1/lib/action_dispatch/middleware/cookies.rb:168:in `signed_or_encrypted'

The same action works half of the time.

Thanks

**Comment by abstractj** [comment]
@djannot could you please gist your Gemfile and if possible the steps to reproduce?

**Comment by pierrickrouxel** [comment]
Hi, I have the exact same problem.

I run the rails application on IBM Websphere Application Server

JRuby 1.7.4
Rails 4.0.0

My Gemfile :
https://gist.github.com/pierrickrouxel/6450676

**Comment by pierrickrouxel** [comment]
It's possible to reproduce error with a warbler executable war. I have the problem only when rails is in production mode.

**Comment by djannot** [comment]
Hi Bruno,

Sorry for the delay, here is my Gemfile.

And, thanks for your help ;-)

 Gemfilehttps://docs.google.com/file/d/0Byj8c8coPn8HbGhVTVA1NF9XZ28/edit?usp=drive_web

2013/9/3 Bruno Oliveira notifications@github.com

**Comment by abstractj** [comment]
@pierrickrouxel Good morning my friend, sorry for the uber delay. I just wrote this application with TorqueBox to reproduce your issue https://github.com/abstractj/torquebox-krypt-example

I hope it helps, let me know

**Comment by pierrickrouxel** [comment]
Hi ! Sorry. I forgot to close this issue. The bug doesn't appears with later JRuby versions. Thanks.

**Comment by vipulnsward** [comment]
Thanks @pierrickrouxel and @abstractj for confirming!
