### ISSUE TITLE
Krypt::Provider::ServiceNotAvailableError in Rails 

### ISSUE THREAD

**Issue by jvrmaia** [krypt/krypt#42]
Devise provide a lib from Rails to generate tokens, [see here](https://github.com/plataformatec/devise/blob/master/lib/devise/token_generator.rb#L50), and testing in `rails console` this works fine:

```
irb(main):002:0> OpenSSL::PKCS5.pbkdf2_hmac_sha1("s3cr37_70k3n", "s3cr37", 2**16, 64)
=> "\xB4N2FY\xE8`\xA2l(E\xCC\xB8]~@\x157-\xDCG\xBB\x7F;55F\xF09N\x9A(R\xDB[Z\xF3c\xB52\xBD\x7F\xD8\x93[\x16\x7F\xD2\xB3\x80~\x8E1\x8F\x00\x0Ej8\\,q\xF4\x87\xBE"
```

But, running `rails server` this not work as expected:

```
Krypt::Provider::ServiceNotAvailableError in Namespace::SomeController#create
```

Searching on issues, I found some issues similar and tried all possible fixes without success.

My env:
- JRuby 1.7.9
- Oracle Java 1.7u45
- Rails 3.2.16
- Devise 3.2.2
- OSX 10.9.1 with OpenSSL 1.0.1f

Observation: in other issues people try gems `krypt` and `jruby-openssl` in Gemfile but this not work for me.

**Comment by jvrmaia** [comment]
Hi, I solved the problem here changing my Gemfile:

``` ruby
gem 'krypt', path: '../krypt/'
gem 'krypt-core', path: '../krypt-core-java'
gem 'krypt-provider-jdk', path: '../krypt-provider-jdk'
```

**Comment by abstractj** [comment]
@jvrmaia sorry for taking so long getting back to you, we've been struggling to keep up the pace but it's hard with so many things going on.

If you had changed your Gemfile, I think it can be fixed with the next release of Krypt. Either way, I will make sure to reproduce your issue here before our next release.

Thanks in advance.

**Comment by jvrmaia** [comment]
thanks @abstractj !

I tried understand better the problem to make sure about where fix it.
If I understand, now JRuby provide krypt as default so I don't need put krypt in my Gemfile or require in source code.

Is it possible to be a problem in JRuby to load krypt? Comparing JRuby 9000 (branch master) and JRuby 1.7.x they changed significantly the implementation. (I not tried JRuby 9000)

I'll try keep online on IRC channel to help with this issue.

**Comment by abstractj** [comment]
@jvrmaia some bits of Krypt were landed on JRuby already. I will try to reproduce your issue today to see what's going on and get back to you.

Thanks for your help and patience.

**Comment by abstractj** [comment]
@jvrmaia ahoy! So basically Krypt bits were incorporated to JRuby (https://github.com/jruby/jruby/tree/jruby-1_7/lib/ruby/shared/krypt) and you don't need to include it at your Gemfile if you are running JRuby. I wrote an example here, not sure if that helps https://github.com/abstractj/torquebox-krypt-example

Either way let me know how it goes, or just send to me the steps to reproduce.

**Comment by jvrmaia** [comment]
@abstractj I followed your README but your example not rendered HTML. (I did it fast so maybe is my fault)

Today will be hard to try reproduce the problem, maybe, tomorrow I can give a feedback about it.

thks!

**Comment by abstractj** [comment]
@jvrmaia weird :/ ping me whenever you want on IRC and we can figure this out

**Comment by jvrmaia** [comment]
I tried reproduce bug in another applications but without "success".

Debugging my app I found it, at this line https://github.com/krypt/krypt/blob/master/lib/krypt/provider/provider.rb#L12

when my gemfile not contains krypt provide return Krypt::Provider::Native and when my gemfile contains all krypt gems (krypt, core, jdk) pointing to github return Krypt::Provider::JDK

I will keep trying and reporting news 

thks!

**Comment by abstractj** [comment]
@jvrmaia during this week I will try to run Krypt with trinidad + devise and see how it goes, thanks again

**Comment by jvrmaia** [comment]
hey, I tried krypt "0.0.2.rc1" on my Gemfile and works well. =D

**Comment by abstractj** [comment]
@jvrmaia Huzzah! I'm closing atm, but feel free to reopen if the problem returns or open a new issue if you find anything else.

Thank you

**Comment by jvrmaia** [comment]
ok, thanks!
